services:
  postgres:
    image: social-postgres
    build: .
    restart: always
    ports:
      - ${DB_PORT}:5432
    # environment:
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: social_postgres

volumes:
  postgres_data:
